scene_2d_physics_source_files = files(
	'collision_shape_2d.cpp',
	'character_body_2d.cpp',
	'physics_body_2d.cpp',
	'kinematic_body_2d.cpp',
	'rigid_body_2d.cpp',
	'static_body_2d.cpp',
)

scene_2d_physics_headers = files(
	'collision_shape_2d.hpp',
	'character_body_2d.hpp',
	'physics_body_2d.hpp',
	'kinematic_body_2d.hpp',
	'rigid_body_2d.hpp',
	'static_body_2d.hpp',
)