scene_resources_source_files = files(
	'file_texture.cpp',
	'resource.cpp',
	'texture2d.cpp',
	'tile_set.cpp',
    'world2d.cpp',
)

scene_resources_headers = files(
	'file_texture.hpp',
	'resource.hpp',
	'texture2d.hpp',
	'tile_set.hpp',
	'resource_format_loader.hpp',
	'texture_format_loader.hpp',
    'world2d.hpp',
)

subdir('physics')

scene_resources_source_files += scene_resources_physics_source_files
scene_resources_headers += scene_resources_physics_headers
