scene_resources_physics_source_files = files(
	'capsule_shape_2d.cpp',
	'circle_shape_2d.cpp',
	'concave_polygon_shape_2d.cpp',
	'convex_polygon_shape_2d.cpp',
	'rectangle_shape_2d.cpp',
	'segment_shape_2d.cpp',
	'shape_2d.cpp',
	'world_boundary_shape_2d.cpp',
)

scene_resources_physics_headers = files(
	'capsule_shape_2d.hpp',
	'circle_shape_2d.hpp',
	'concave_polygon_shape_2d.hpp',
	'convex_polygon_shape_2d.hpp',
	'rectangle_shape_2d.hpp',
	'segment_shape_2d.hpp',
	'shape_2d.hpp',
	'world_boundary_shape_2d.hpp',
)